# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-13 07:01
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190513_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
